import { Diploma } from 'src/app/models/diploma.interface';

export const DIPLOMAS: Diploma[] = [
  {
    name: 'Accesibilidad Web',
    url: 'assets/diplomas/accesibilidad-web.pdf',
    id: 1,
    hours: 15,
    date_end: '08/2020',
  },
  {
    name: 'Algoritmos y estructuras de datos',
    url: 'assets/diplomas/algoritmos-estucturas-datos.pdf',
    id: 2,
    hours: 22,
    date_end: '07/2020',
  },
  {
    name: 'Algoritmos',
    url: 'assets/diplomas/algoritmos.pdf',
    id: 3,
    hours: 300,
    date_end: '08/2020',
  },
  {
    name: 'Angular material',
    url: 'assets/diplomas/angualr-material.pdf',
    id: 4,
    hours: 7,
    date_end: '11/2021',
  },
  {
    name: 'Angular 11',
    url: 'assets/diplomas/angular-11.pdf',
    id: 5,
    hours: 18,
    date_end: '05/2021',
  },
  {
    name: 'Angular Academia',
    url: 'assets/diplomas/angular-academia.pdf',
    id: 6,
    hours: 10,
    date_end: '02/2020',
  },
  {
    name: 'Angular Avanzado',
    url: 'assets/diplomas/angular-avanzado.pdf',
    id: 7,
    hours: 33,
    date_end: '02/2021',
  },
  {
    name: 'Angular cero a experto',
    url: 'assets/diplomas/angular-cero-a-experto.pdf',
    id: 8,
    hours: 36,
    date_end: '01/2021',
  },
  {
    name: 'Angular components',
    url: 'assets/diplomas/angular-components.pdf',
    id: 9,
    hours: 3,
    date_end: '06/2022',
  },
  {
    name: 'Angular Core',
    url: 'assets/diplomas/angular-core.pdf',
    id: 10,
    hours: 9,
    date_end: '12/2021',
  },
  {
    name: 'Angular Forms Depth',
    url: 'assets/diplomas/angular-forms-depth.pdf',
    id: 11,
    hours: 7,
    date_end: '10/2021',
  },
  {
    name: 'Angular Forms',
    url: 'assets/diplomas/angular-forms.pdf',
    id: 12,
    hours: 18,
    date_end: '11/2020',
  },
  {
    name: 'Angular NgRx',
    url: 'assets/diplomas/angular-ngrx.pdf',
    id: 13,
    hours: 12,
    date_end: '11/2021',
  },
  {
    name: 'Angular Performance',
    url: 'assets/diplomas/angular-performance.pdf',
    id: 14,
    hours: 13,
    date_end: '11/2020',
  },
  {
    name: 'Angular Profesional',
    url: 'assets/diplomas/angular-profesional.pdf',
    id: 15,
    hours: 15,
    date_end: '11/2020',
  },
  {
    name: 'Angular Router',
    url: 'assets/diplomas/angular-router.pdf',
    id: 16,
    hours: 5,
    date_end: '10/2021',
  },
  {
    name: 'Angular RxJs',
    url: 'assets/diplomas/angular-rxjs.pdf',
    id: 17,
    hours: 6,
    date_end: '11/2021',
  },
  {
    name: 'Angular Sockets',
    url: 'assets/diplomas/angular-sockets.pdf',
    id: 18,
    hours: 10,
    date_end: '05/2022',
  },
  {
    name: 'Angular Testing',
    url: 'assets/diplomas/angular-testing.pdf',
    id: 19,
    hours: 5,
    date_end: '11/2021',
  },
  {
    name: 'Angular Universal',
    url: 'assets/diplomas/angular-universal.pdf',
    id: 20,
    hours: 5,
    date_end: '05/2022',
  },
  {
    name: 'Animaciones Web',
    url: 'assets/diplomas/animaciones-web.pdf',
    id: 21,
    hours: 22,
    date_end: '06/2020',
  },
  {
    name: 'Anti Bribery and You!',
    url: 'assets/diplomas/anti-bribery.pdf',
    id: 22,
    hours: 10,
    date_end: '10/2021',
  },
  {
    name: 'Api REST',
    url: 'assets/diplomas/api-rest.pdf',
    id: 23,
    hours: 18,
    date_end: '10/2020',
  },
  {
    name: 'Asincronismo con Javascript',
    url: 'assets/diplomas/asincronismo-js.pdf',
    id: 24,
    hours: 16,
    date_end: '04/2020',
  },
  {
    name: 'Javascript Básico',
    url: 'assets/diplomas/basico-javascript.pdf',
    id: 25,
    hours: 20,
    date_end: '04/2020',
  },
  {
    name: 'Bootstrap',
    url: 'assets/diplomas/bootstrap.pdf',
    id: 26,
    hours: 6,
    date_end: '06/2020',
  },
  {
    name: 'Calidad de proyectos',
    url: 'assets/diplomas/calidad-proyectos-web.pdf',
    id: 27,
    hours: 6,
    date_end: '06/2022',
  },
  {
    name: 'Competencias digitales',
    url: 'assets/diplomas/competencias-digitales.pdf',
    id: 28,
    hours: 40,
    date_end: '10/2020',
  },
  {
    name: 'Conflicts of Interest',
    url: 'assets/diplomas/conflictos-interes.pdf',
    id: 29,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'CSS Grid Layout',
    url: 'assets/diplomas/css-grid-layout.pdf',
    id: 30,
    hours: 14,
    date_end: '05/2020',
  },
  {
    name: 'Data protection',
    url: 'assets/diplomas/data-protection.pdf',
    id: 31,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Defeating Social Engineers',
    url: 'assets/diplomas/defeating-social-engineers.pdf',
    id: 32,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Desarrollo con Angular',
    url: 'assets/diplomas/desarrollo-angular.pdf',
    id: 33,
    hours: 40,
    date_end: '12/2020',
  },
  {
    name: 'Desarrollo de Apps Mobile',
    url: 'assets/diplomas/desarrollo-apps-mobile.pdf',
    id: 34,
    hours: 40,
    date_end: '09/2020',
  },
  {
    name: 'Flujo de desarrollo moderno con Codestream',
    url: 'assets/diplomas/desarrollo-moderno-codestream.pdf',
    id: 35,
    hours: 10,
    date_end: '12/2020',
  },
  {
    name: 'Introducción al despliegue de aplicaciones',
    url: 'assets/diplomas/despliegue-apps.pdf',
    id: 36,
    hours: 11,
    date_end: '11/2020',
  },
  {
    name: 'Debugging con Chrome Devtools',
    url: 'assets/diplomas/devtools.pdf',
    id: 37,
    hours: 18,
    date_end: '07/2020',
  },
  {
    name: 'Diseño para programadores',
    url: 'assets/diplomas/diploma-diseno-programadores.pdf',
    id: 38,
    hours: 11,
    date_end: '06/2020',
  },
  {
    name: 'Estructuras de datos con Javascript',
    url: 'assets/diplomas/diploma-estructuras-datos.pdf',
    id: 39,
    hours: 22,
    date_end: '01/2021',
  },
  {
    name: 'Introducción a la Web: Historia y funcionamiento de internet',
    url: 'assets/diplomas/diploma-introweb.pdf',
    id: 40,
    hours: 12,
    date_end: '11/2020',
  },
  {
    name: 'Sistema de diseño para desarrolladores',
    url: 'assets/diplomas/diseno-desarrolladores.pdf',
    id: 41,
    hours: 29,
    date_end: '06/2020',
  },
  {
    name: 'Ecmascript 6+',
    url: 'assets/diplomas/ecmascript-6.pdf',
    id: 42,
    hours: 20,
    date_end: '04/2020',
  },
  {
    name: 'Ensglish B1',
    url: 'assets/diplomas/english-b1.pdf',
    id: 43,
    hours: 20,
    date_end: '07/2021',
  },
  {
    name: 'Figma para frontends',
    url: 'assets/diplomas/figma.pdf',
    id: 44,
    hours: 15,
    date_end: '07/2021',
  },
  {
    name: 'Foundation',
    url: 'assets/diplomas/foundation.pdf',
    id: 45,
    hours: 14,
    date_end: '06/2020',
  },
  {
    name: 'Frontend Developer',
    url: 'assets/diplomas/frontend-developer.pdf',
    id: 46,
    hours: 30,
    date_end: '03/2020',
  },
  {
    name: 'Programación Funcional',
    url: 'assets/diplomas/funcional-js.pdf',
    id: 47,
    hours: 16,
    date_end: '09/2020',
  },
  {
    name: 'Fundamentos de Javascript',
    url: 'assets/diplomas/fundamentos-javascript.pdf',
    id: 48,
    hours: 22,
    date_end: '03/2020',
  },
  {
    name: 'Git y Github',
    url: 'assets/diplomas/git-github.pdf',
    id: 49,
    hours: 18,
    date_end: '04/2020',
  },
  {
    name: 'Global Code of Conduct',
    url: 'assets/diplomas/global-code-conduct.pdf',
    id: 50,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Angular',
    url: 'assets/diplomas/angular.pdf',
    id: 51,
    hours: 30,
    date_end: '10/2020',
  },
  {
    name: 'Handing Infromation Safely',
    url: 'assets/diplomas/handing-information.pdf',
    id: 52,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Desarrollo Web Online',
    url: 'assets/diplomas/html5-css3.pdf',
    id: 53,
    hours: 22,
    date_end: '03/2020',
  },
  {
    name: 'Coding for Beginners',
    url: 'assets/diplomas/html-css.pdf',
    id: 54,
    hours: 18,
    date_end: '06/2020',
  },
  {
    name: 'Definitivo de HTML y CSS',
    url: 'assets/diplomas/html-css-2020.pdf',
    id: 55,
    hours: 23,
    date_end: '08/2020',
  },
  {
    name: 'Solid foundational HTML, CSS and Javascript',
    url: 'assets/diplomas/html-css-javascript.pdf',
    id: 56,
    hours: 20,
    date_end: '07/2020',
  },
  {
    name: 'HTML y CSS en práctica',
    url: 'assets/diplomas/html-practico.pdf',
    id: 57,
    hours: 25,
    date_end: '05/2020',
  },
  {
    name: 'Incident Reporting',
    url: 'assets/diplomas/incident-report.pdf',
    id: 58,
    hours: 12,
    date_end: '10/2021',
  },
  {
    name: 'Inclusive Leadership for All',
    url: 'assets/diplomas/inclusive-leadership.pdf',
    id: 59,
    hours: 14,
    date_end: '11/2021',
  },
  {
    name: 'Inclusive Leadership for All part 2',
    url: 'assets/diplomas/inclusive-leadership-2.pdf',
    id: 60,
    hours: 8,
    date_end: '11/2021',
  },
  {
    name: 'Fundamentos de Ingenieria de Software',
    url: 'assets/diplomas/ingenieria.pdf',
    id: 61,
    hours: 13,
    date_end: '03/2020',
  },
  {
    name: 'Introducción a C',
    url: 'assets/diplomas/introcuccion-c.pdf',
    id: 62,
    hours: 18,
    date_end: '06/2020',
  },
  {
    name: 'Introducción al desarrollo web parte 1',
    url: 'assets/diplomas/introduccion-desarrollo-web-1.pdf',
    id: 63,
    hours: 40,
    date_end: '08/2020',
  },
  {
    name: 'Introducción al desarrollo web parte 2',
    url: 'assets/diplomas/introduccion-desarrollo-web-2.pdf',
    id: 64,
    hours: 40,
    date_end: '08/2020',
  },
  {
    name: 'Ionic 6',
    url: 'assets/diplomas/ionic-6.pdf',
    id: 65,
    hours: 30,
    date_end: '10/2021',
  },
  {
    name: 'Ionic 4',
    url: 'assets/diplomas/ionic-avanzado.pdf',
    id: 66,
    hours: 13,
    date_end: '12/2020',
  },
  {
    name: 'Javascript Moderno',
    url: 'assets/diplomas/javascript-moderno.pdf',
    id: 67,
    hours: 18,
    date_end: '07/2022',
  },
  {
    name: 'Javascript Engine (V8) y el navegador',
    url: 'assets/diplomas/javascript-navegador.pdf',
    id: 68,
    hours: 8,
    date_end: '07/2020',
  },
  {
    name: 'Javascript Profesional',
    url: 'assets/diplomas/javascript-profesional.pdf',
    id: 69,
    hours: 26,
    date_end: '08/2020',
  },
  {
    name: 'De jQuery a Javascript',
    url: 'assets/diplomas/jquery-js.pdf',
    id: 70,
    hours: 16,
    date_end: '04/2020',
  },
  {
    name: 'Javascript de cero hasta los detalles (ES5)',
    url: 'assets/diplomas/js5.pdf',
    id: 71,
    hours: 8,
    date_end: '03/2021',
  },
  {
    name: 'Java Server Faces Practical',
    url: 'assets/diplomas/jsf.pdf',
    id: 72,
    hours: 5,
    date_end: '11/2021',
  },
  {
    name: 'Introduction to Leadership',
    url: 'assets/diplomas/leadership.pdf',
    id: 73,
    hours: 10,
    date_end: '11/2021',
  },
  {
    name: 'Less',
    url: 'assets/diplomas/less.pdf',
    id: 74,
    hours: 10,
    date_end: '05/2020',
  },
  {
    name: 'Lógica de Programación',
    url: 'assets/diplomas/logica-programacion.pdf',
    id: 75,
    hours: 3,
    date_end: '03/2020',
  },
  {
    name: 'Materialize',
    url: 'assets/diplomas/materialize.pdf',
    id: 76,
    hours: 8,
    date_end: '10/2020',
  },
  {
    name: 'Buenas prácticas para la escritura de código',
    url: 'assets/diplomas/mejor-codigo.pdf',
    id: 77,
    hours: 20,
    date_end: '09/2020',
  },
  {
    name: 'Metodología de desarrollo de Software',
    url: 'assets/diplomas/metodologias.pdf',
    id: 78,
    hours: 6,
    date_end: '02/2022',
  },
  {
    name: 'Responsive Desing: Maquetación Mobile First',
    url: 'assets/diplomas/mobile-first.pdf',
    id: 79,
    hours: 25,
    date_end: '12/2020',
  },
  {
    name: 'NgRx',
    url: 'assets/diplomas/ngrx.pdf',
    id: 80,
    hours: 7,
    date_end: '11/2021',
  },
  {
    name: 'Gestión de dependencias y paquetes con NPM',
    url: 'assets/diplomas/npm.pdf',
    id: 81,
    hours: 9,
    date_end: '09/2020',
  },
  {
    name: 'Programación Orientada a Objectos',
    url: 'assets/diplomas/oop.pdf',
    id: 82,
    hours: 20,
    date_end: '07/2020',
  },
  {
    name: 'Optimización de carga de sitios Web',
    url: 'assets/diplomas/optimizacion-web.pdf',
    id: 83,
    hours: 4,
    date_end: '09/2020',
  },
  {
    name: 'Introducción a los Algoritmos de Ordenamiento',
    url: 'assets/diplomas/ordenamiento.pdf',
    id: 84,
    hours: 9,
    date_end: '10/2020',
  },
  {
    name: 'Password Security',
    url: 'assets/diplomas/password-security.pdf',
    id: 85,
    hours: 7,
    date_end: '10/2021',
  },
  {
    name: 'Pensamiento Lógico',
    url: 'assets/diplomas/pensamiento-logico.pdf',
    id: 86,
    hours: 10,
    date_end: '04/2020',
  },
  {
    name: 'Pishing',
    url: 'assets/diplomas/pishing.pdf',
    id: 87,
    hours: 5,
    date_end: '10/2021',
  },
  {
    name: 'POSTCSS',
    url: 'assets/diplomas/postcss.pdf',
    id: 88,
    hours: 11,
    date_end: '06/2020',
  },
  {
    name: 'Postman',
    url: 'assets/diplomas/postman.pdf',
    id: 89,
    hours: 10,
    date_end: '10/2020',
  },
  {
    name: 'Maquetación en CSS',
    url: 'assets/diplomas/practico-css.pdf',
    id: 90,
    hours: 20,
    date_end: '05/2020',
  },
  {
    name: 'Preprocesadores de CSS',
    url: 'assets/diplomas/preprocesadores.pdf',
    id: 91,
    hours: 22,
    date_end: '05/2020',
  },
  {
    name: 'Prevención de blanqueo de capitales',
    url: 'assets/diplomas/prevencion-blanqueo.pdf',
    id: 92,
    hours: 22,
    date_end: '11/2021',
  },
  {
    name: 'Prevención de Riesgos Penales',
    url: 'assets/diplomas/prevencion-de-riesgos.pdf',
    id: 93,
    hours: 18,
    date_end: '11/2021',
  },
  {
    name: 'Prework: Buenas práctias y entorno de desarrollo',
    url: 'assets/diplomas/prework.pdf',
    id: 94,
    hours: 12,
    date_end: '04/2020',
  },
  {
    name: 'Prework: Buenas práctias y entorno de desarrollo en Windows',
    url: 'assets/diplomas/prework-windows.pdf',
    id: 95,
    hours: 10,
    date_end: '12/2020',
  },
  {
    name: 'Productividad Personal',
    url: 'assets/diplomas/productividad-personal.pdf',
    id: 96,
    hours: 40,
    date_end: '09/2020',
  },
  {
    name: 'Programación Básica',
    url: 'assets/diplomas/programacion-basica.pdf',
    id: 97,
    hours: 20,
    date_end: '03/2020',
  },
  {
    name: 'Programación Estructurada',
    url: 'assets/diplomas/programacion-estructurada.pdf',
    id: 98,
    hours: 14,
    date_end: '07/2020',
  },
  {
    name: 'Protecting Mobile data and devices',
    url: 'assets/diplomas/protecting-mobile-devices.pdf',
    id: 99,
    hours: 15,
    date_end: '10/2021',
  },
  {
    name: 'PWA - Aplicaciones Web Progresivas: De cero a experto',
    url: 'assets/diplomas/pwa.pdf',
    id: 100,
    hours: 15,
    date_end: '02/2021',
  },
  {
    name: 'Progresive Web Apps with Angular',
    url: 'assets/diplomas/pwa-angular.pdf',
    id: 101,
    hours: 11,
    date_end: '11/2020',
  },
  {
    name: 'React',
    url: 'assets/diplomas/react.pdf',
    id: 102,
    hours: 8,
    date_end: '01/2021',
  },
  {
    name: 'ReactiveX - RxJs: De cero hasta los detalles',
    url: 'assets/diplomas/reactivex-rxjs.pdf',
    id: 103,
    hours: 10,
    date_end: '01/2021',
  },
  {
    name: 'React: De cero a experto (Hooks)',
    url: 'assets/diplomas/react-mern.pdf',
    id: 104,
    hours: 44,
    date_end: '05/2021',
  },
  {
    name: 'Redux en Angular con NgRx',
    url: 'assets/diplomas/redux.pdf',
    id: 105,
    hours: 13,
    date_end: '01/2021',
  },
  {
    name: 'Responsive Desing',
    url: 'assets/diplomas/responsive-design.pdf',
    id: 106,
    hours: 26,
    date_end: '04/2020',
  },
  {
    name: 'Responsive Web Desing',
    url: 'assets/diplomas/responsive-web.pdf',
    id: 107,
    hours: 300,
    date_end: '08/2020',
  },
  {
    name: 'Responsive Web Desing - Create a Responsive Website',
    url: 'assets/diplomas/responsive-web-desing.pdf',
    id: 108,
    hours: 20,
    date_end: '07/2020',
  },
  {
    name: 'RxJs nivel Pro',
    url: 'assets/diplomas/rxjs-pro.pdf',
    id: 109,
    hours: 4,
    date_end: '06/2021',
  },
  {
    name: 'SASS',
    url: 'assets/diplomas/sass.pdf',
    id: 110,
    hours: 16,
    date_end: '06/2020',
  },
  {
    name: 'SASS - The Complete Guide',
    url: 'assets/diplomas/sass-complete.pdf',
    id: 111,
    hours: 6,
    date_end: '11/2021',
  },
  {
    name: 'Clousures y Scope en Javascript',
    url: 'assets/diplomas/scope.pdf',
    id: 112,
    hours: 13,
    date_end: '08/2020',
  },
  {
    name: 'Seguridad ante Covid-19',
    url: 'assets/diplomas/seguridad-covid.pdf',
    id: 113,
    hours: 18,
    date_end: '10/2021',
  },
  {
    name: 'Sitios Web con Wordpress',
    url: 'assets/diplomas/seo-wordpress.pdf',
    id: 114,
    hours: 15,
    date_end: '10/2020',
  },
  {
    name: 'Router para Single Page App con Javascript',
    url: 'assets/diplomas/singlepage-app.pdf',
    id: 115,
    hours: 9,
    date_end: '09/2020',
  },
  {
    name: 'Sistemas de Diseño',
    url: 'assets/diplomas/sistemas-diseno.pdf',
    id: 116,
    hours: 37,
    date_end: '07/2020',
  },
  {
    name: 'SOLID y Clean Code',
    url: 'assets/diplomas/solid.pdf',
    id: 117,
    hours: 7,
    date_end: '05/2022',
  },
  {
    name: 'SPA con Javascript Vanilla',
    url: 'assets/diplomas/spa-javascript.pdf',
    id: 118,
    hours: 12,
    date_end: '09/2020',
  },
  {
    name: 'Overview of Strategy',
    url: 'assets/diplomas/strategy.pdf',
    id: 119,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Stylus',
    url: 'assets/diplomas/stylus.pdf',
    id: 120,
    hours: 16,
    date_end: '06/2020',
  },
  {
    name: 'Tax Evasion and Terrorist Financing',
    url: 'assets/diplomas/tax-evation.pdf',
    id: 121,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Terminal y Linea de Comandos',
    url: 'assets/diplomas/terminal.pdf',
    id: 122,
    hours: 12,
    date_end: '06/2020',
  },
  {
    name: 'Reglamiento General de Protección de Datos',
    url: 'assets/diplomas/titulo.pdf',
    id: 123,
    hours: 10,
    date_end: '01/2022',
  },
  {
    name: 'Transformación Digital para el Empleo',
    url: 'assets/diplomas/transformacion-digital.pdf',
    id: 124,
    hours: 40,
    date_end: '09/2020',
  },
  {
    name: 'Overview of Transformation',
    url: 'assets/diplomas/transformation.pdf',
    id: 125,
    hours: 10,
    date_end: '10/2021',
  },
  {
    name: 'Fundamentos de Typescript',
    url: 'assets/diplomas/typescript.pdf',
    id: 126,
    hours: 17,
    date_end: '09/2020',
  },
  {
    name: 'Typescript con Angular',
    url: 'assets/diplomas/typescript-angular.pdf',
    id: 127,
    hours: 12,
    date_end: '10/2020',
  },
  {
    name: 'Typescript guía Completa',
    url: 'assets/diplomas/typescript-pro.pdf',
    id: 128,
    hours: 9,
    date_end: '06/2022',
  },
  {
    name: 'The Value of Difference',
    url: 'assets/diplomas/value-of-difference.pdf',
    id: 129,
    hours: 16,
    date_end: '11/2021',
  },
  {
    name: 'Vue básico',
    url: 'assets/diplomas/vuejs.pdf',
    id: 130,
    hours: 19,
    date_end: '10/2020',
  },
  {
    name: 'Git y Github. Sistema de control de versiones',
    url: 'assets/diplomas/git-github-versiones.pdf',
    id: 131,
    hours: 12,
    date_end: '07/2022',
  },
  {
    name: 'Gestionar la calidad del código con SonarQube',
    url: 'assets/diplomas/sonarqube.pdf',
    id: 132,
    hours: 4,
    date_end: '07/2022',
  },
  {
    name: 'Codificación segura y estándares de seguridad.',
    url: 'assets/diplomas/codificacion-segura.pdf',
    id: 133,
    hours: 3,
    date_end: '07/2022',
  },
  {
    name: 'Jenkins',
    url: 'assets/diplomas/jenkins.pdf',
    id: 134,
    hours: 3,
    date_end: '07/2022',
  },
  {
    name: 'Next.js',
    url: 'assets/diplomas/next.pdf',
    id: 135,
    hours: 46,
    date_end: '08/2022',
  },
  {
    name: 'Agile + Scrum',
    url: 'assets/diplomas/agile-scrum.pdf',
    id: 136,
    hours: 3,
    date_end: '08/2022',
  },
  {
    name: 'Scrum y Agile',
    url: 'assets/diplomas/scrum-agile.pdf',
    id: 137,
    hours: 8,
    date_end: '08/2022',
  },
  {
    name: 'Angular Animations',
    url: 'assets/diplomas/angular-animations.pdf',
    id: 138,
    hours: 7,
    date_end: '08/2022',
  },
  {
    name: 'Diseño Web Morderno',
    url: 'assets/diplomas/web-moderno.pdf',
    id: 139,
    hours: 18,
    date_end: '08/2022',
  },
  {
    name: 'Introducción a Jira para gestión de proyectos',
    url: 'assets/diplomas/web-moderno.pdf',
    id: 140,
    hours: 2,
    date_end: '08/2022',
  },
  {
    name: 'Angular Security Masterclass',
    url: 'assets/diplomas/angular-security.pdf',
    id: 141,
    hours: 8,
    date_end: '08/2022',
  },
  {
    name: 'NestJs - Introducción',
    url: 'assets/diplomas/nestjs-intro.pdf',
    id: 142,
    hours: 2,
    date_end: '08/2022',
  },
  {
    name: 'Electron',
    url: 'assets/diplomas/electron.pdf',
    id: 143,
    hours: 13,
    date_end: '08/2022',
  },
  {
    name: 'Jira with real-world examples',
    url: 'assets/diplomas/jira-confluence.pdf',
    id: 144,
    hours: 12,
    date_end: '09/2022',
  },
  {
    name: 'Object Oriented Design Foundations',
    url: 'assets/diplomas/uml.pdf',
    id: 145,
    hours: 2,
    date_end: '09/2022',
  },
  {
    name: 'Proceso de Desarrollo Seguro',
    url: 'assets/diplomas/ssdlc.pdf',
    id: 146,
    hours: 2,
    date_end: '09/2022',
  },
  {
    name: 'Git Bootcamp',
    url: 'assets/diplomas/git-bootcamp.pdf',
    id: 147,
    hours: 17,
    date_end: '10/2022',
  },
  {
    name: 'Introducción a Docker',
    url: 'assets/diplomas/docker-introduction.pdf',
    id: 148,
    hours: 4,
    date_end: '09/2022',
  },
  {
    name: 'Introducción al Testing',
    url: 'assets/diplomas/testing-introduccion.pdf',
    id: 149,
    hours: 3,
    date_end: '10/2022',
  },
  {
    name: 'Node de cero a experto',
    url: 'assets/diplomas/node.pdf',
    id: 150,
    hours: 29,
    date_end: '10/2022',
  },
];
