import { Diploma } from 'src/app/models/diploma.interface';

export const DIPLOMAS: Diploma[] = [
  {
    name: 'Accesibilidad Web',
    url: 'assets/diplomas/accesibilidad-web.pdf',
    id: 1,
    hours: 15,
    date_end: '08/2020',
  },
  {
    name: 'Algoritmos y estructuras de datos',
    url: 'assets/diplomas/algoritmos-estucturas-datos.pdf',
    id: 2,
    hours: 22,
    date_end: '07/2020',
  },
  {
    name: 'Algoritmos',
    url: 'assets/diplomas/algoritmos.pdf',
    id: 3,
    hours: 300,
    date_end: '08/2020',
  },
  {
    name: 'Angular material',
    url: 'assets/diplomas/angualr-material.pdf',
    id: 4,
    hours: 7,
    date_end: '11/2021',
  },
  {
    name: 'Angular 11',
    url: 'assets/diplomas/angular-11.pdf',
    id: 5,
    hours: 18,
    date_end: '05/2021',
  },
  {
    name: 'Angular Academia',
    url: 'assets/diplomas/angular-academia.pdf',
    id: 6,
    hours: 10,
    date_end: '02/2020',
  },
  {
    name: 'Angular Avanzado',
    url: 'assets/diplomas/angular-avanzado.pdf',
    id: 7,
    hours: 33,
    date_end: '02/2021',
  },
  {
    name: 'Angular cero a experto',
    url: 'assets/diplomas/angular-cero-a-experto.pdf',
    id: 8,
    hours: 36,
    date_end: '01/2021',
  },
  {
    name: 'Angular components',
    url: 'assets/diplomas/angular-components.pdf',
    id: 9,
    hours: 3,
    date_end: '06/2022',
  },
  {
    name: 'Angular Core',
    url: 'assets/diplomas/angular-core.pdf',
    id: 10,
    hours: 9,
    date_end: '12/2021',
  },
  {
    name: 'Angular Forms Depth',
    url: 'assets/diplomas/angular-forms-depth.pdf',
    id: 11,
    hours: 7,
    date_end: '10/2021',
  },
  {
    name: 'Angular Forms',
    url: 'assets/diplomas/angular-forms.pdf',
    id: 12,
    hours: 18,
    date_end: '11/2020',
  },
  {
    name: 'Angular NgRx',
    url: 'assets/diplomas/angular-ngrx.pdf',
    id: 13,
    hours: 12,
    date_end: '11/2021',
  },
  {
    name: 'Angular Performance',
    url: 'assets/diplomas/angular-performance.pdf',
    id: 14,
    hours: 13,
    date_end: '11/2020',
  },
  {
    name: 'Angular Profesional',
    url: 'assets/diplomas/angular-profesional.pdf',
    id: 15,
    hours: 15,
    date_end: '11/2020',
  },
  {
    name: 'Angular Router',
    url: 'assets/diplomas/angular-router.pdf',
    id: 16,
    hours: 5,
    date_end: '10/2021',
  },
  {
    name: 'Angular RxJs',
    url: 'assets/diplomas/angular-rxjs.pdf',
    id: 17,
    hours: 6,
    date_end: '11/2021',
  },
  {
    name: 'Angular Sockets',
    url: 'assets/diplomas/angular-sockets.pdf',
    id: 18,
    hours: 10,
    date_end: '05/2022',
  },
  {
    name: 'Angular Testing',
    url: 'assets/diplomas/angular-testing.pdf',
    id: 19,
    hours: 5,
    date_end: '11/2021',
  },
  {
    name: 'Angular Universal',
    url: 'assets/diplomas/angular-universal.pdf',
    id: 20,
    hours: 5,
    date_end: '05/2022',
  },
  {
    name: 'Animaciones Web',
    url: 'assets/diplomas/animaciones-web.pdf',
    id: 21,
    hours: 22,
    date_end: '06/2020',
  },
  {
    name: 'Anti Bribery and You!',
    url: 'assets/diplomas/anti-bribery.pdf',
    id: 22,
    hours: 10,
    date_end: '10/2021',
  },
  {
    name: 'Api REST',
    url: 'assets/diplomas/api-rest.pdf',
    id: 23,
    hours: 18,
    date_end: '10/2020',
  },
  {
    name: 'Asincronismo con Javascript',
    url: 'assets/diplomas/asincronismo-js.pdf',
    id: 24,
    hours: 16,
    date_end: '04/2020',
  },
  {
    name: 'Javascript Básico',
    url: 'assets/diplomas/basico-javascript.pdf',
    id: 25,
    hours: 20,
    date_end: '04/2020',
  },
  {
    name: 'Bootstrap',
    url: 'assets/diplomas/bootstrap.pdf',
    id: 26,
    hours: 6,
    date_end: '06/2020',
  },
  {
    name: 'Calidad de proyectos',
    url: 'assets/diplomas/calidad-proyectos.pdf',
    id: 27,
    hours: 6,
    date_end: '06/2022',
  },
  {
    name: 'Competencias digitales',
    url: 'assets/diplomas/competencias-digitales.pdf',
    id: 28,
    hours: 40,
    date_end: '10/2020',
  },
  {
    name: 'Conflicts of Interest',
    url: 'assets/diplomas/conflictos-intereses.pdf',
    id: 29,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'CSS Grid Layout',
    url: 'assets/diplomas/css-grid-layout.pdf',
    id: 30,
    hours: 14,
    date_end: '05/2020',
  },
  {
    name: 'Data protection',
    url: 'assets/diplomas/data-protection.pdf',
    id: 31,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Defeating Social Engineers',
    url: 'assets/diplomas/defeating-social-engineers.pdf',
    id: 32,
    hours: 20,
    date_end: '10/2021',
  },
  {
    name: 'Desarrollo con Angular',
    url: 'assets/diplomas/desarrollo-angular.pdf',
    id: 33,
    hours: 40,
    date_end: '12/2020',
  },
];
